**Instructions**
1. Follow the instructions in each of the cell
2. Make sure not to delete any of the cells

In [145]:
#import statements
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.feature_selection import f_regression
import pickle
import hashlib

### Input Data

In [146]:
#Load and print the data
data=pd.read_csv('./input/input.csv')
#Enter the answer here
data

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10
5,GP,M,16,U,LE3,T,4,3,services,other,...,5,4,2,1,2,5,10,15,15,15
6,GP,M,16,U,LE3,T,2,2,other,other,...,4,4,4,1,1,3,0,12,12,11
7,GP,F,17,U,GT3,A,4,4,other,teacher,...,4,1,4,1,1,1,6,6,5,6
8,GP,M,15,U,LE3,A,3,2,services,other,...,4,2,2,1,1,1,0,16,18,19
9,GP,M,15,U,GT3,T,3,4,other,other,...,5,5,1,1,1,5,0,14,15,15
10,GP,F,15,U,GT3,T,4,4,teacher,health,...,3,3,3,1,2,2,0,10,8,9
11,GP,F,15,U,GT3,T,2,1,services,other,...,5,2,2,1,1,4,4,10,12,12
12,GP,M,15,U,LE3,T,4,4,health,services,...,4,3,3,1,3,5,2,14,14,14
13,GP,M,15,U,GT3,T,4,3,teacher,other,...,5,4,3,1,2,3,2,10,10,11
14,GP,M,15,U,GT3,A,2,2,other,other,...,4,5,2,1,1,3,0,14,16,16
15,GP,F,16,U,GT3,T,4,4,health,other,...,4,4,4,1,2,2,4,14,14,14
16,GP,F,16,U,GT3,T,4,4,services,services,...,3,2,3,1,2,2,6,13,14,14
17,GP,F,16,U,GT3,T,3,3,other,other,...,5,3,2,1,1,4,4,8,10,10
18,GP,M,17,U,GT3,T,3,2,services,services,...,5,5,5,2,4,5,16,6,5,5
19,GP,M,16,U,LE3,T,4,3,health,other,...,3,1,3,1,3,5,4,8,10,10
20,GP,M,15,U,GT3,T,4,3,teacher,other,...,4,4,1,1,1,1,0,13,14,15
21,GP,M,15,U,GT3,T,4,4,health,health,...,5,4,2,1,1,5,0,12,15,15
22,GP,M,16,U,LE3,T,4,2,teacher,other,...,4,5,1,1,3,5,2,15,15,16
23,GP,M,16,U,LE3,T,2,2,other,other,...,5,4,4,2,4,5,0,13,13,12
24,GP,F,15,R,GT3,T,2,4,services,health,...,4,3,2,1,1,5,2,10,9,8
25,GP,F,16,U,GT3,T,2,2,services,services,...,1,2,2,1,3,5,14,6,9,8
26,GP,M,15,U,GT3,T,2,2,other,other,...,4,2,2,1,2,5,2,12,12,11
27,GP,M,15,U,GT3,T,4,2,health,services,...,2,2,4,2,4,1,4,15,16,15
28,GP,M,16,U,LE3,A,3,4,services,other,...,5,3,3,1,1,5,4,11,11,11
29,GP,M,16,U,GT3,T,4,4,teacher,teacher,...,4,4,5,5,5,5,16,10,12,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1014,MS,F,18,U,GT3,T,3,3,services,services,...,4,3,2,1,3,3,6,13,12,13
1015,MS,F,17,U,LE3,T,4,4,at_home,at_home,...,2,3,4,1,1,1,4,15,14,15
1016,MS,F,17,R,GT3,T,1,2,other,services,...,3,2,2,1,2,3,0,13,13,13
1017,MS,M,18,R,GT3,T,1,3,at_home,other,...,3,3,4,2,4,3,0,8,10,9
1018,MS,M,18,U,LE3,T,4,4,teacher,services,...,4,2,2,2,2,5,0,15,16,16
1019,MS,F,17,R,GT3,T,1,1,other,services,...,5,2,1,1,2,1,0,8,8,9
1020,MS,F,18,U,GT3,T,2,3,at_home,services,...,5,2,3,1,2,4,0,10,10,10
1021,MS,F,18,R,GT3,T,4,4,other,teacher,...,3,2,2,4,2,5,0,7,5,0
1022,MS,M,18,R,LE3,T,1,2,at_home,services,...,4,3,3,2,3,3,3,9,10,10
1023,MS,F,17,U,GT3,T,2,2,other,at_home,...,3,4,3,1,1,3,8,10,11,12
1024,MS,F,17,R,GT3,T,1,2,other,other,...,3,5,5,1,3,1,4,7,8,9
1025,MS,F,18,R,LE3,T,4,4,other,other,...,5,4,4,1,1,1,0,15,17,17
1026,MS,F,18,R,GT3,T,1,1,other,other,...,4,3,2,1,2,4,4,10,11,12
1027,MS,F,19,R,GT3,T,1,1,at_home,other,...,4,3,3,1,1,3,4,7,8,9
1028,MS,F,18,R,LE3,T,4,4,teacher,services,...,5,4,3,3,4,2,1,13,14,14
1029,MS,F,18,U,GT3,T,3,3,other,other,...,4,1,3,1,2,1,1,16,16,16
1030,MS,F,17,R,GT3,T,3,1,at_home,other,...,4,5,4,2,3,1,10,8,9,9
1031,MS,M,18,U,GT3,T,4,4,teacher,teacher,...,3,2,4,1,4,2,4,17,18,19
1032,MS,M,18,R,GT3,T,2,1,other,other,...,4,4,3,1,3,5,0,7,7,0
1033,MS,M,17,U,GT3,T,2,3,other,services,...,4,4,3,1,1,3,4,14,15,16
1034,MS,M,19,R,GT3,T,1,1,other,services,...,4,3,2,1,3,5,0,5,8,0
1035,MS,M,18,R,GT3,T,4,2,other,other,...,5,4,3,4,3,3,0,7,7,0
1036,MS,F,18,R,GT3,T,2,2,at_home,other,...,5,3,3,1,3,4,0,14,17,15
1037,MS,F,17,U,GT3,T,4,3,teacher,other,...,5,5,4,1,1,1,0,6,9,11
1038,MS,F,18,R,GT3,T,4,4,teacher,at_home,...,4,4,3,2,2,5,4,7,9,10
1039,MS,F,19,R,GT3,T,2,3,services,other,...,5,4,2,1,2,5,4,10,11,10
1040,MS,F,18,U,LE3,T,3,1,teacher,services,...,4,3,4,1,1,1,4,15,15,16
1041,MS,F,18,U,GT3,T,1,1,other,other,...,1,1,1,1,1,5,6,11,12,9
1042,MS,M,17,U,LE3,T,3,1,services,services,...,2,4,5,3,4,2,6,10,10,10
1043,MS,M,18,R,LE3,T,3,2,services,other,...,4,4,1,3,4,5,4,10,11,11

### Data Cleaning

Check if there are any null values in data.

If so, replace the null values with column mean

In [147]:
data.isnull().values.any()

False

### Exploratory Data Analysis

**Question:1**

Which school has more number of students? Gabriel Pereira or Mousinho da Silveira

Assign the number of students in that school to the variable **q1**

In [148]:
#a=data.groupby(["school"]).count().max(level=0)
#print(a)
#Enter the answer here
q1=772

**Question 2:**

Which group of students have more opportunity in schooling? Rural or Urban?

Assign the number of rural students or the number of urban students who has more opportunity to **q2**

In [149]:
#b=data.groupby(["address"]).count().max(level=0)
#print(b)
#Enter the answer here
q2=759

**Question 3**

Which group of students(rural or urban) shows more interest in each of the schools?

*Instructions*
1. Find the number of rural and Urban areas students in each school and find the greatest among them.
2. Store them in respective variable

In [150]:
#c=data.groupby(["school","address"]).count()
#print(c)


#Store the number of rural students or the number of urban students who had more opportunity to study in GP school
#Enter the answer here
q3=631


#Store the number of rural students or the number of urban students who had more opportunity to study in GP school
#Enter the answer here
q4=144

**Question 4**

Which age group of students are more interested in GP school? Assign the specific age to the variable.

In [151]:
#d=data[data.school=='GP'].groupby(["age"]).count()
#print(d)


#Enter the answer here
q5=16

**Question 5**

Find out the average Daily consumption of alcohol in rural area and Urban area separately.

In [152]:

#data[data.address=='R'].Dalc.mean()
#Average Daily Consumption of Alcohol in Rural Area

#Enter the answer here
q6=1.5894736842105264

#print(q6)

#Average Daily Consumption of Alcohol in Urban Area

#Enter the answer here
q7=1.458498023715415
#data[data.address=='U'].Dalc.mean()
#print(q7)

**Question 6**

Find out the average Daily consumption of alcohol in rural areas and Urban areas separately specific to each school and assign the greater average value to the respective variable of schools.

In [153]:
#f=data.groupby(["school","address"]).Dalc.mean()
#GP school greater average in rural or urban
#print(f)
#Enter the answer here
q8=1.517730



#MS school greater average in rural or urban

#Enter the answer here
q9=1.659722

#print(data.dtypes)

**Question 7**

**Let us find the variable which made the maximum impact on the Final grade of students with pearson coefficient.**

*Note: All the variables used for calculating pearson coefficient must be numerical.*



A predictor that has a low p-value is likely to be a meaningful addition to your model because changes in the predictor's value are related to changes in the response variable.

Conversely, a larger (insignificant) p-value suggests that changes in the predictor are not associated with changes in the response.


*Instructions*
1. Consider G3 as target variable `Y`. 
2. Remove the variables G1, G2. Consider the rest as predictor variables
3. Calculate the P value of all variables (hint: fregression and label encoding using cat.codes)
4. Variables with P-values less than 0.05 (95% confidence) are considered to be the `Predictor Variables`. Form a dataframe `X` with it.
5. Calculate the correlation between the predictor variable and target variable
6. Find the highest Correlation value in the column `G3` which depicts the variable that made the greatest impact on G3.
7. Print the variable that made greatest impact on `G3`.
8. Assign the highest correlation value and the highest impacted attribute to the respective variable

Note: Make sure to compare the absolute value of the correlation values

In [154]:
'''from sklearn.preprocessing import LabelEncoder
from scipy.stats import pearsonr
Y=data.G3
data2=data
X=data[:-3]

print(data.corr())

col=['school','sex','address', 'famsize','Pstatus', 'Mjob','Fjob', 'reason','guardian','schoolsup','famsup', 'paid','activities','nursery','higher','internet','romantic']  
for name in col:
    X[name] = LabelEncoder().fit_transform(X[name])
print(X.data_corr())

f,p=f_regression(X,Y)
print(f)
print(p)
#for colname in X.columns:
    #print(colname)
    #print(pearsonr(X[colname],Y)) '''
#Highest impact attribute
#higher (0.23657799566492788, 9.549431631711794e-15)
#Enter the answer here
q10='failures'



#highest correlation value

#Enter the answer here
q11=0.383145

## Run the below cells to save your answers in pickle file

In [155]:
def make_pickle1(file_name, obj):
    with open(file_name, 'wb') as f:
        pickle.dump(geth(obj), f, pickle.HIGHEST_PROTOCOL)

In [156]:
def make_pickle2(file_name, obj):
    with open(file_name, 'wb') as f:
        pickle.dump(obj, f, pickle.HIGHEST_PROTOCOL)

In [157]:
def get_pickle(file_name):
    with open(file_name, 'rb') as f:
        return pickle.load(f)

In [158]:
def geth(obj):
    obj = str(obj).encode()
    m = hashlib.md5()
    m.update( bytes(obj) )
    return m.hexdigest()

In [159]:
def pickling():
    make_pickle1('q1.pickle', q1)
    make_pickle1('q2.pickle', q2)
    make_pickle1('q3.pickle', q3)
    make_pickle1('q4.pickle', q4)
    make_pickle1('q5.pickle', q5)
    make_pickle2('q6.pickle', q6)
    make_pickle2('q7.pickle', q7)
    make_pickle2('q8.pickle', q8)
    make_pickle2('q9.pickle', q9)
    make_pickle1('q10.pickle', q10)
    make_pickle2('q11.pickle', q11)
    
    
pickling()